name: Run Benchmark and Deploy Results
on:
    push:
        branches:
            - master
permissions:
    contents: write
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
        
            - name: Install and Build
              run: |
                npm ci && npm test && npm run main
            
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: results/html
